# ambiente de desenvolvimento com:
# apache 2.4, php 7.0, mysql ultima versao, dados
# salvos em: /var/mysql/data, arquivo de configuração
# para inicializar mysql config/mysql/my.cnf
#
#

web:
    image: fredericomartini/php:7.0-dev
    container_name: apache2-php
    links: 
        - db
    volumes: 
        - "/var/www/:/var/www/"
    ports:
        - "7000:80"
    command: "apache2ctl -D FOREGROUND"

db:
    image: mysql:latest
    container_name: db-mysql
    environment: 
        MYSQL_ROOT_PASSWORD: "mysql"
    volumes_from:
        - data
    ports:
        - "localhost:3306:3306"
    command: "echo [mysqld]\nsql_mode=\"STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION;\" > /etc/mysql/conf.d/config.cnf"
    command: "/usr/bin/mysqld_safe"

data:
    image: busybox:latest
    volumes:
        #- "./config/mysql/:/etc/mysql/" #nao utilizado, setando comando acima, útil p/ quando não é clonado repo, somente script de install
        - "/var/mysql/data:/var/lib/mysql"
