# ambiente de desenvolvimento com:
# apache 2.4, php 7.0, mysql ultima versao, dados
# salvos em: /var/mysql/data
#
#

 web:
    image: fredericomartini/php:7.0-dev
    container_name: apache2-php
    links: 
        - db
    volumes: 
        - "/var/www/:/var/www/"
    ports:
        - "7000:80"
    command: "apache2ctl -D FOREGROUND"

 db:
    image: postgres:latest
    container_name: db-postgres
    environment: 
        POSTGRES_PASSWORD: "postgres"
    volumes_from:
        - data
    ports:
        - "localhost:5432:5432" 

 data:
    image: busybox:latest
    volumes:
        - "/var/lib/postgresql/data:/var/lib/postgresql/data"

